test.message=hello from config server

app.jwt.secret=sdfgaklwfjhloi23irh928holakjhfnilo2uyirolakjhf9238yfuoej
app.jwt.access-expiration-ms=900000
app.jwt.refresh-expiration-ms=604800000 

server.port=80

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# AUTH SERVICE
# Gateway: /api/auth/register -> auth_service: /auth/register
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://auth-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1


# USER SERVICE
# Gateway: /api/users/me -> user-service: /users/me
spring.cloud.gateway.server.webflux.routes[1].id=user-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://user-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/users/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=StripPrefix=1


# CHAT SERVICE
# Gateway: /api/chat/** -> chat_service: /chat/**
spring.cloud.gateway.server.webflux.routes[2].id=chat-service-rest
spring.cloud.gateway.server.webflux.routes[2].uri=lb://chat-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/chat/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=StripPrefix=1

#CHAT SERVICE
# Gateway: /chat-websocket
spring.cloud.gateway.server.webflux.routes[3].id=chat-service-ws
spring.cloud.gateway.server.webflux.routes[3].uri=lb:ws://chat-service
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/ws,/ws/**

#CORS Service
spring.cloud.gateway.server.webflux.globalcors.add-to-simple-url-handler-mapping=true
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOriginPatterns=http://localhost:5173,http://127.0.0.1:5173,http://192.168.*.*:5173
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,PATCH,DELETE,OPTIONS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowCredentials=true
