test.message=hello from config server

app.jwt.secret=sdfgaklwfjhloi23irh928holakjhfnilo2uyirolakjhf9238yfuoej
app.jwt.access-expiration-ms=900000
app.jwt.refresh-expiration-ms=604800000 

server.port=80

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# AUTH SERVICE
# Gateway: /api/auth/register -> auth_service: /auth/register
spring.cloud.gateway.server.webmvc.routes[0].id=auth-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://auth-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0].name=Path
spring.cloud.gateway.server.webmvc.routes[0].predicates[0].args._genkey_0=/api/auth/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0].name=Authenticate
spring.cloud.gateway.server.webmvc.routes[0].filters[1].name=StripPrefix
spring.cloud.gateway.server.webmvc.routes[0].filters[1].args._genkey_0=1


# USER SERVICE
# Gateway: /api/users/me -> user-service: /users/me
spring.cloud.gateway.server.webmvc.routes[1].id=user-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://user-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0].name=Path
spring.cloud.gateway.server.webmvc.routes[1].predicates[0].args._genkey_0=/api/users/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0].name=Authenticate
spring.cloud.gateway.server.webmvc.routes[1].filters[1].name=StripPrefix
spring.cloud.gateway.server.webmvc.routes[1].filters[1].args._genkey_0=1


# CHAT SERVICE
# Gateway: /api/chat/** -> chat_service: /chat/**
spring.cloud.gateway.server.webmvc.routes[2].id=chat-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://chat-service
spring.cloud.gateway.server.webmvc.routes[2].predicates[0].name=Path
spring.cloud.gateway.server.webmvc.routes[2].predicates[0].args._genkey_0=/api/chat/**
spring.cloud.gateway.server.webmvc.routes[2].filters[0].name=Authenticate
spring.cloud.gateway.server.webmvc.routes[2].filters[1].name=StripPrefix
spring.cloud.gateway.server.webmvc.routes[2].filters[1].args._genkey_0=1